[package]
name = "midgar_life"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
cgmath = "0.12.0"
midgar = { git = "https://github.com/mystal/midgar-engine" }
rand = "0.3.16"
